#!/system/bin/sh
# ========================================

#disable Key Backlight

echo begin set Key Backlight - KB
echo KB - set permissions rw
chmod 0666 /sys/class/leds/button-backlight/brightness
echo KB - set Key Backlight 0
echo "0" > /sys/class/leds/button-backlight/brightness
echo KB - set permissions ro
chmod 0444 /sys/class/leds/button-backlight/brightness
echo KB - BAM



